@api = http://54.147.221.20:8080/users

GET {{api}}

###

POST {{api}}/post
Content-Type: application/json

{
    "fullName": "Caterina Sandoval",
    "email": "CatSan@gmail.com",
    "phoneNum": "985123412",
    "password": "catlover",
    "avatar": ""
}


###

GET {{api}}/get/id/2


###

GET {{api}}/get/CatSan@gmail.com/catlover


###

DELETE {{api}}/delete/3


###

GET {{api}}/count


###

PUT {{api}}/put/5
Content-Type: application/json

{
    "fullName": "Barbatos",
    "email": "Obeyme@gmail.cm",
    "phoneNum": "98733321",
    "password": "awa123",
    "avatar": "https://pfps.gg/assets/pfps/1184-bear.png"
}